C 
	FUNCTION CITFND(Z6)
C
C FIND CITY AT LOCATION Z6, RETURN INDEX INTO CityLocation()
C
	INCLUDE "EMPIRE.INC/NOLIST"
C
	DO 100 I=1,70
100	IF (CityLocation(I).EQ.Z6) GOTO 200
	IF (.NOT.PASS) RETURN
	CALL STROUT("CITFND ERROR",2)
	RETURN
200	CITFND=I
	RETURN
	END