	BYTE FUNCTION DECODE(Z6)
C
C UNPACK MAP DEFINITION FILE
C	D() = MAP DEFINITION FROM MAP FILE
C	Z6 = LOCATION
C	DECODE = CHARACTER AT Z6
C
C MAPS ARE ENCODED USING MOD 3 ARITHMETIC TO FIT 9 CHARACTERS INTO ONE 16-BIT
C  WORD.
C
	IMPLICIT INTEGER(A-Z)
	INTEGER MSKTAB(9)
	INTEGER*2 D(667)
	BYTE ASCII(3)
	DATA ASCII/".","+","*"/
	DATA MSKTAB/1,3,9,27,81,243,729,2187,6561/
	COMMON/MAP/D
C
	ICityLocation=((Z6-1)/9)+1
	IY=MOD(Z6-1,9)+1
	DECODE=ASCII(MOD(D(ICityLocation)/MSKTAB(IY),3)+1)
	RETURN
	END