C 
	SUBROUTINE DIST(Z6,ILA)
C
C THIS SUBROUTINE SETS UnitTimer SO THAT THE ARMY WON"T GET
C OFF THE TROOP TRANSPORT PREMATURELY
C 
	INCLUDE "EMPIRE.INC/NOLIST"
C
	ID=2*IDIST(Z6,ILA)+1
	DO 100 L=1+CArmyStart,UpperIndex(9)+CArmyStart
100	IF (UnitLocation(L).EQ.Z6) UnitTimer(L-CArmyStart)=ID
	RETURN
	END