	FUNCTION EDGER(I)
C
C RETURN NUMBER OF SEA SQUARES THAT ARE ADJACENT TO LOCATION I
C
	INCLUDE "EMPIRE.INC/NOLIST"
C
	EDGER=0
	DO 100 IA=1,8
100	IF (MasterMap(I+MoveOffset(IA+1)).EQ.".") EDGER=EDGER+1
	RETURN
	END