C 
	FUNCTION EXPL
C 
C THIS SUBROUTINE SEARCHES FOR UNKNOWN TERRITORY AND RETURNS A VALUE
C IN EXPL.
C 
	INCLUDE "EMPIRE.INC/NOLIST"
C
	IF (FULL.EQ.2) GOTO 300
	BEGPOS=START
	GOTO 200
100	IF ((EMAP(POSIT).EQ." ").AND.(ORDER(POSIT).EQ.0)) GOTO 400
200	POSIT=POSIT+STEP
	IF (POSIT.LT.5900) GOTO 100
	START=START+1
	POSIT=START
	IF (START.EQ.BEGPOS+37) GOTO 300
	GOTO 100
300	EXPL=0
	FULL=2
C	CALL LIB$SET_CURSOR(1,1)
C	TYPE 999,POSIT,STEP,START,BEGPOS,KNOWN
C999	FORMAT("+POSIT,STEP,START,BEGPOS,KNOWN:",5I5$)
	RETURN
400	EXPL=POSIT
	RETURN
	END