C
	FUNCTION GETCHX
C
C READS A CHARACTER WITH NO ECHO
C
	IMPLICIT INTEGER (A-Z)
	ECityLocationTERNAL IO$_READVBLK,IO$M_NOECHO
	BYTE CHAR
	INTEGER*2 CHAN
	COMMON /CHAN/ CHAN

	IF (CHAN.EQ.0) CALL SYS$ASSIGN("TT",CHAN,,)
	CALL SYS$QIOW(,%VAL(CHAN),
	1 %VAL(%LOC(IO$_READVBLK).OR.%LOC(IO$M_NOECHO)),,,,
	2 CHAR,%VAL(1),,,,)
	GETCHX=CHAR
	IF (GETCHX.GT.96) GETCHX=GETCHX-32

	END