C 
	SUBROUTINE HEAD(OWN1,Y,NUM,Z6,H1)
C
	INCLUDE "EMPIRE.INC/NOLIST"
C
	CALL LIB$SET_CURSOR(1,1)
	CALL IDEN(OWN1)
	CALL DECPRT(Y)
	CALL STROUT(" at",10)
	CALL DECPRT(Z6)
	CALL LIB$ERASE_LINE
	CALL STSOUT(MYCODE(NUM))
	IF (OWN1 .EQ. "F") THEN
	   CALL LIB$SET_CURSOR(1,60)
	   CALL STROUT("Range:",10)
	   CALL DECPRT(RANGE(Y))
	   ENDIF
	IF ((OWN1.NE."F").AND.(OWN1.NE."A")) THEN
	   CALL LIB$SET_CURSOR(1,60)
	   CALL STROUT("Hits left:",10)
	   CALL DECPRT(H1)
	   ENDIF
	RETURN
	END