	SUBROUTINE HELP
C
C HELP - PRINT HELP FILE
C
	CALL LIB$GERASE_PAGE(1,1)
	CALL STROUT("EMPIRE.HLP  (see EMPIRE.DOC for more detail)",1)
	CALL STROUT("ORDERS MODE-----------
	1	MOVE MODE-------------	EDIT MODE-------------",0)
	CALL LIB$SET_CURSOR(7,1)
	CALL STROUT("A: Stay in Move mode",1)
	CALL STROUT("C: Give 1 free move",1)
	CALL STROUT("G: GIGI color terminal",1)
	CALL STROUT("H: This text",1)
	CALL STROUT("J: Enter Edit mode",1)
	CALL STROUT("M: Enter Move mode",1)
	CALL STROUT("N: Give n free moves",1)
	CALL STROUT("P: Refresh sector",1)
	CALL STROUT("Q: Quit game",1)
	CALL STROUT("R: Display round #",1)
	CALL STROUT("S: Clear screen",1)
	CALL STROUT("T: Print out map",1)
	CALL STROUT("V: Save game",0)
C
	CALL LIB$SET_CURSOR(4,25)
	CALL STROUT("QWE: Movement",0)
	CALL LIB$SET_CURSOR(5,25)
	CALL STROUT("A D  direction",0)
	CALL LIB$SET_CURSOR(6,25)
	CALL STROUT("ZCityLocationC",0)
	CALL LIB$SET_CURSOR(7,25)
	CALL STROUT("<space>: Sit",0)
	CALL LIB$SET_CURSOR(8,25)
	CALL STROUT("G: Sleep till full T,C",0)
	CALL LIB$SET_CURSOR(9,25)
	CALL STROUT("H: This text",0)
	CALL LIB$SET_CURSOR(10,25)
	CALL STROUT("I: Set direction",0)
	CALL LIB$SET_CURSOR(11,25)
	CALL STROUT("J: Enter Edit mode",0)
	CALL LIB$SET_CURSOR(12,25)
	CALL STROUT("K: Wake piece",0)
	CALL LIB$SET_CURSOR(13,25)
	CALL STROUT("L: Set city direction",0)
	CALL LIB$SET_CURSOR(14,25)
	CALL STROUT("O: Cancel Auto moves",0)
	CALL LIB$SET_CURSOR(15,25)
	CALL STROUT("P: Refresh screen",0)
	CALL LIB$SET_CURSOR(16,25)
	CALL STROUT("R: Random for Armies",0)
	CALL LIB$SET_CURSOR(17,25)
	CALL STROUT("S: Sentry",0)
	CALL LIB$SET_CURSOR(18,25)
	CALL STROUT("?: Display function",0)
C
	CALL LIB$SET_CURSOR(4,49)
	CALL STROUT("QWE: Cursor",0)
	CALL LIB$SET_CURSOR(5,49)
	CALL STROUT("A D  direction",0)
	CALL LIB$SET_CURSOR(6,49)
	CALL STROUT("ZCityLocationC",0)
C	CALL LIB$SET_CURSOR(8,49)
C	CALL STROUT("G: Sleep til full T,C",0)
	CALL LIB$SET_CURSOR(9,49)
	CALL STROUT("H: This text",0)
	CALL LIB$SET_CURSOR(10,49)
	CALL STROUT("I: Set direction",0)
	CALL LIB$SET_CURSOR(11,49)
	CALL STROUT("K: Wake anything",0)
	CALL LIB$SET_CURSOR(12,49)
	CALL STROUT("M: Set path start",0)
	CALL LIB$SET_CURSOR(13,49)
	CALL STROUT("N: Set path end",0)
	CALL LIB$SET_CURSOR(14,49)
	CALL STROUT("O: Exit Edit mode",0)
	CALL LIB$SET_CURSOR(15,49)
	CALL STROUT("P: Change sector",0)
	CALL LIB$SET_CURSOR(16,49)
	CALL STROUT("R: Random for armies",0)
	CALL LIB$SET_CURSOR(17,49)
	CALL STROUT("S: Sentry ",0)
	CALL LIB$SET_CURSOR(18,49)
	CALL STROUT("Y: Set city production",0)
	CALL LIB$SET_CURSOR(19,49)
	CALL STROUT("?: Display function",1)
	CALL STROUT("Piece---Yours-Enemy-Moves-Hits-Cost
	1	Piece---Yours-Enemy-Moves-Hits-Cost",1)
	CALL STROUT("Army        A a       1    1     5
	1	Transport   T t       2    3    30",1)
	CALL STROUT("Fighter     F f       4    1    10
	1	Cruiser     R r       2    8    50",1)
	CALL STROUT("Destroyer   D d       2    3    20
	1	Carrier     C c       2    8    60",1)
	CALL STROUT("Submarine   S s       2    2    25
	1	Battleship  B b       2   12    75",0)
C
	RETURN
	END