C 
	INTEGER FUNCTION HITS(OWN)
	IMPLICIT INTEGER(A-Z)
	INTEGER B(8)
	BYTE ATYP(8),OWN
	DATA ATYP/"A","F","D","S","T","R","C","B"/
	DATA B/ 1 , 1,  3,  2,  3,  8,  8, 12 /
C
	HITS=0
	DO 100 I=1,8
	IF (OWN.EQ.ATYP(I)) GOTO 200
100	CONTINUE
	RETURN
200	HITS=B(I)
	RETURN
	END