C 
	SUBROUTINE IDEN(OWN)
C
	INCLUDE "EMPIRE.INC/NOLIST"
C
	IF ((OWN.GE."a").AND.(OWN.LE."t")) CALL STROUT("Enemy",10)
	IF ((OWN.LE."T").AND.(OWN.GE."A")) CALL STROUT("Your",10)
	IF ((OWN.EQ."A").OR.(OWN.EQ."a")) GOTO 100
	IF ((OWN.EQ."F").OR.(OWN.EQ."f")) GOTO 200
	IF ((OWN.EQ."D").OR.(OWN.EQ."d")) GOTO 300
	IF ((OWN.EQ."S").OR.(OWN.EQ."s")) GOTO 400
	IF ((OWN.EQ."T").OR.(OWN.EQ."t")) GOTO 500
	IF ((OWN.EQ."R").OR.(OWN.EQ."r")) GOTO 600
	IF ((OWN.EQ."C").OR.(OWN.EQ."c")) GOTO 700
C
C THEN IT IS A BATTLESHIP'
C
	CALL STROUT("Battleship",10)
	RETURN
100	CALL STROUT("Army",10)
	RETURN
200	CALL STROUT("Fighter",10)
	RETURN
300	CALL STROUT("Destroyer",10)
	RETURN
400	CALL STROUT("Submarine",10)
	RETURN
500	CALL STROUT("Troop Transport",10)
	RETURN
600	CALL STROUT("Cruiser",10)
	RETURN
700	CALL STROUT("Aircraft Carrier",10)
	RETURN
	END