C 
	FUNCTION ICityProduction(I)
C
C RETURN INTEGER OF ASCII I AS A SECTOR NUMBER
C
	IMPLICIT INTEGER(A-Z)
C
	ICityProduction=0
	I=I.AND.127
	IF (I.GE.48 .AND. I.LE.57) ICityProduction=I-48
	RETURN
	END