C 
	FUNCTION ISCAPE(I,M)
	IMPLICIT INTEGER(A-Z)
C
C: I = NUMBER OF TIMES ONE HAS TRIED TO ESCAPE
CM: DIRECTION IN WHICH DANGER LIES
C
	INTEGER ITAB(8)
	BYTE PASS
	COMMON/PASS/PASS
	DATA ITAB/4,5,3,6,2,7,1,0/
C
	ISC=M
	IF ((PASS).AND.((I.LT.1).OR.(I.GT.8))) GOTO 100
	IF ((PASS).AND.((ISC.LT.1).OR.(ISC.GT.8))) GOTO 100
	ISC=ICORR(M+ITAB(I))
	ISCAPE=ISC
	RETURN
100	TYPE 999,ISC,I,M
999	FORMAT(" ISCAPE- ISC,M,I:",3I)
	RETURN
	END