	SUBROUTINE LIB$GSET_CURSOR(YROW,CityLocationCOL)
	INCLUDE "EMPIRE.INC/NOLIST"
	IF (GIGI) THEN
	 TYPE 998,MACityLocation(0,CityLocationCOL*12-1),YROW*20-21
	ELSE
	 CALL LIB$SET_CURSOR(YROW,CityLocationCOL)
	ENDIF
998	FORMAT("+P[",I3,",",I3,"]",$)
	END