C
C NUM = city number
C E will be chosen production
C
	SUBROUTINE PHASIN(NUM,E)
C
C PROMPT FOR CITY PRODUCTION TYPE, SET PROD ACCORDINGLY
C
	INCLUDE "EMPIRE.INC/NOLIST"
C
	E=GETCHX()
	DO 200 I=1,8
200	IF (E.EQ.PHAZE(I)) GOTO 300
	CALL HUH
	E=" "
	RETURN			'IF HE DOESN"T DO IT RIGHT, LEAVE IT

300	CityProduction(NUM)=PH(I)
	FOUND(NUM)=MDATE+6*CityProduction(NUM)
	RETURN
	END