	FUNCTION RND(IHIGH)
C
	IMPLICIT INTEGER(A-Z)
	INTEGER*2 TIME(4)
	EQUIVALENCE (TIME(2),SEED)
	REAL MTH$RANDOM
	DATA SEED/0/
	IF (SEED.EQ.0) CALL SYS$GETTIM(TIME)
	RND=IFICityLocation(MTH$RANDOM(SEED)*IHIGH)
	END