C
	SUBROUTINE STASIS(Z6,LOC)
C
C CHECK IF ARMY #LOC, AT Z6, IS NEAR THE ENEMY, IF SO WAKE HIM UP
C
	INCLUDE "EMPIRE.INC/NOLIST"
C
	DO 200 I=1,8
	AB=ReferenceMap(Z6+MoveOffset(I+1))		'**
	IF ((AB.GE."a").AND.(AB.LE."t")) GOTO 100
	IF (AB.EQ."X") GOTO 100
	IF (AB.NE."*") GOTO 200
	IF (ReferenceMap(Z6).EQ."F") GOTO 200
100	MYCODE(LOC)=0
	GOTO 300
200	CONTINUE
300	RETURN
	END