C
	SUBROUTINE STROUT(LINE,N)
C
C TYPE OUT ASCIZ TECityLocationT "LINE" AND WHERE N IS A TWO DIGIT NUMBER "AB"
C A=NUMBER OF TRAILING SPACES (1-4),
C B=0 MEANS DO NOTHING ELSE, B=1 MEANS CLEAR LINE AND TYPE CRLF,
C B=3 MEANS CLEAR LINE
C 
	IMPLICIT INTEGER(A-Z)
	LOGICAL*1 LINE(80),BLANKS(4)
	DATA BLANKS/" "," "," "," "/
C
C FIND LENGTH OF STRING AND PRINT IT.
	J=1
	DO 100 I=1,80
	  IF (LINE(I).EQ.0) GOTO 200
	  IF (LINE(I).NE." ") J=I
100	CONTINUE
200	TYPE 300,(LINE(I),I=1,J)
300	FORMAT("+",<J>A1,$)
C
C NOW SEPARATE PIECES OF N
	J=MIN0(IABS(N/10),4)
	IF (J.NE.0) TYPE 300,(BLANKS(I),I=1,J)
C
	J=MOD(N,10)
	IF (J.NE.0) CALL LIB$ERASE_LINE
	IF (J.EQ.1) TYPE 400
400	FORMAT(1X)
	RETURN
	END