C===============================================================================
C TEST4
C -----
C
C Appears to be something to assist in debugging, displays information about the
C path being planned.
C===============================================================================
	SUBROUTINE TEST4(Z6,FLAG,DIR,MOVE1,MOVNUM,BEG,END,AG2,FLAG2)
C
C TEST SUBROUTINE FOR PATH, DISPLAYS CURRENT PATH PROGRESS
C
	INCLUDE "EMPIRE.INC/NOLIST"
	INTEGER AG2(100)
C 
	CALL CURSOR(Z6-IADJST)
	IF (FLAG.NE.1001) E=GETCHX()	'WAIT FOR CHAR IF TRACE MODE
 
	ICityLocation="G"				'DISPLAY CURRENT MOVE ON MAP
	IF (FLAG2.EQ.1) TYPE 999,ICityLocation
	ICityLocation="H"
	IF (FLAG2.EQ.2) TYPE 999,ICityLocation
	IF (FLAG.EQ.1001) RETURN
C					PROCESS THIS CHAR
	IF (E.EQ." ") RETURN		'SPACE, CONTINUE
	IF (E.EQ."G") GOTO 100		'G, DISPLAY G2 ARRAY
 
	CALL LIB$SET_CURSOR(1,1)	'IF NOT SPACE OR "G", SHOW PATH VARIABLES
	TYPE 998,Z6,MOVE1,MOVNUM
999	FORMAT("+",A1$)
998	FORMAT(" Z6:",I4," MOVE1:",I1," MOVNUM:",I3)
	CALL LIB$SET_CURSOR(2,1)
	TYPE 997,BEG,END,IADJST,DIR,FLAG
997	FORMAT(" BEG:"I4" END:"I4" IADJST:"I4" TDIR:"I2" FLAG:"I4)
 
	IF (FLAG2 .EQ. 1) TYPE 996
996	FORMAT(" FLAG2: MOVE ")
	IF (FLAG2 .EQ. 2) TYPE 995
995	FORMAT(" FLAG2: SHORE")
	RETURN
 
100	CALL LIB$SET_CURSOR(1,1)
	TYPE 994,AG2
994	FORMAT(1X,16I5)
	RETURN
	END