	SUBROUTINE TRAN(AB)
C
C TRANSLATE OLD ENEMY UNITS TO NEW CHARACTERS
C
	INCLUDE "EMPIRE.INC/NOLIST"
	BYTE OLDE(8),NEWE(8)
	DATA OLDE/"1","2","3","4","5","6","7","8"/
	DATA NEWE/"a","f","d","s","t","r","c","b"/

	DO 10 I=1,8
10	  IF(AB.EQ.OLDE(I)) AB=NEWE(I)
	RETURN
	END